name: Weekly Automated Translation

on:
  schedule:
    - cron: '0 0 * * 0' # Runs every Sunday at midnight automatically
  workflow_dispatch: # Allows manual runs

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install Tools
      run: pip install deep-translator
    - name: Run Script
      env:
        BLOGGER_EMAIL: ${{ secrets.BLOGGER_EMAIL }}
      run: python translator.py
    - name: Commit Changes
      run: |
        git config --global user.name 'Automated Bot'
        git config --global user.email 'bot@://github.com'
        git add .
        git commit -m "Automated weekly translation update" || exit 0
        git push
